loki:
  nodeSelector: 
    device: usbssd    
  config:
    compactor:
      retention_enabled: true
      working_directory: /data/loki/boltdb-shipper-compactor
      shared_store: filesystem
    limits_config:
      retention_period: 2h 
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
  persistence:
    enabled: false
  isDefault: false
